import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/Components/Navbar'
import Container from '@/Components/Container'
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://mocki.io/v1/ee762599-31ae-4a3d-a6c7-d596525945e1`)
  const data = await res.json()
  const myData = Object.keys(data).map(key => {
    return data[key];
})
  // Pass data to the page via props
  return { props: { data } }
}
export default function Home({ data }) {
  console.log(data.texts)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container data={data.texts}/>
    </>
  )
}
