import Head from 'next/head'
import Container from '@/Components/Container'
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://mocki.io/v1/ee762599-31ae-4a3d-a6c7-d596525945e1`)
  const data = await res.json()
  // Pass data to the page via props
  return { props: { data } }
}
export default function Home({ data }) {
  console.log(data.texts)
  return (
    <>
      <Head>
        <title>Athena Square | OA </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container data={data.texts} />
    </>
  )
}
